
server:
  port: 9871

signing:
  key: "345345fsdgsf5345"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.mo: DEBUG

env:
  host:
    local: localhost
    dev: dev.avocadostudio.xyz
  db:
    local:
      port: 3306
      schema: DICT
    dev:
      port: 3306
      schema: DICT

# ====================== DEFAULT ======================

spring:
  profiles: default
  application:
    name: dict
  # The bean 'dataSource', defined in BeanDefinition defined in class path resource
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${env.host.dev}:${env.db.dev.port}/${env.db.dev.schema}?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true

eureka:
  instance:
    hostname: ${env.host.local}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${env.host.local}:8090/user

---

# ====================== DEV ======================

spring:
  profiles: dev
  application:
    name: dict
  # The bean 'dataSource', defined in BeanDefinition defined in class path resource
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${env.host.dev}:${env.db.dev.port}/${env.db.dev.schema}?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true

eureka:
  instance:
    hostname: ${env.host.dev}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${env.host.dev}:8090/user